# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1 # Note ansible-test uses pycodestyle 2.8.0 which is part of this tagged release of flake8
    hooks:
      - id: flake8
        name: Check for Flake8 errors on Python files
        # ignoring errors and selecting line length as per
        # https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_util/controller/sanity/pep8/current-ignore.txt
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.5.0'
    hooks:
    - id: pylint # Use pylintrc file in repository
      name: Check for Linting error on Python files
      description: This hook runs pylint.
      exclude: ^.*(docs|tests).*

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 'v1.23.0'
    hooks:
    - id: yamllint
      name: Check for Linting error on YAML files
      description: This hook runs yamllint.
      entry: yamllint
      language: python
      types: [file, yaml]
      args: [-c=.github/yamllintrc]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        name: Check for ansible-lint errors
        files: \.(yaml|yml)$
        exclude: ansible_collections/arista/cvp/docs

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint
        args:
          - --config=.github/.markdownlint.yaml
          - --ignore-path=.github/.markdownlintignore
          - --fix
