---
- name: Test cv_change_control_v3
  hosts: CloudVision
  connection: local
  gather_facts: false
  vars:
    scheduled_time: "2025-07-01T15:20:00.0Z"
    change:
      name: Leaf 1A Change Control
      notes: Initiated from Ansible Playbook
      activities:
        - action: mlaghealthcheck
          name: Check_LEAF1A_MLAG_Health
          arguments:
            - name: DeviceID
              value: SN-DC1-POD1-LEAF1A
          stage: LEAF1A_MLAG_Health
      stages:
        - name: LEAF1A_MLAG_Health
          mode: parallel

  tasks:
    ######################################
    ##       SCHEDULE AND APPROVE       ##
    ######################################

    - name: Create a change control on {{ inventory_hostname }}
      arista.cvp.cv_change_control_v3:
        state: set
        change: "{{ change }}"
      register: cv_change_control_test

    - name: Schedule a change control on {{ inventory_hostname }} using change_id field
      arista.cvp.cv_change_control_v3:
        state: schedule
        change_id: ["{{ cv_change_control_test.data.id }}"]
        schedule_time: "{{ scheduled_time }}"
      register: cv_schedule_change_control

    - name: Display  result
      run_once: true
      ansible.builtin.debug:
        msg: "{{ cv_schedule_change_control }}"

    - name: Check schedule change control
      ansible.builtin.assert:
        that:
          - cv_schedule_change_control.changed == true
          - cv_schedule_change_control.data.time is defined
          - cv_schedule_change_control.data.value.key.id == cv_change_control_test.data.id
          - cv_schedule_change_control.data.value.schedule.value == "2025-07-01T15:20:00Z"

    - name: Approve a change control on {{ inventory_hostname }} using change_id field
      arista.cvp.cv_change_control_v3:
        state: approve
        change_id: ["{{ cv_change_control_test.data.id }}"]
      register: cv_change_control_approve

    - name: Check change control approve
      ansible.builtin.assert:
        that:
          - cv_change_control_approve.changed == true
          - cv_change_control_approve.data.time is defined
          - cv_change_control_approve.data.value.approve.notes == "Initiated from Ansible Playbook"
          - cv_change_control_approve.data.value.approve.value == true
          - cv_change_control_approve.data.value.key.id == cv_change_control_test.data.id
          - cv_change_control_approve.data.value.version is defined
          - cv_change_control_approve.failed == false

    - name: Remove a change control on {{ inventory_hostname }} using change_id field
      arista.cvp.cv_change_control_v3:
        state: remove
        change_id: ["{{ cv_change_control_test.data.id }}"]

    # SCHEDULE AND APPROVE TOGETHER
    - name: Create a change control on {{ inventory_hostname }}
      arista.cvp.cv_change_control_v3:
        state: set
        change: "{{ change }}"
      register: cv_change_control_test

    - name: Schedule and Approve a change control on {{ inventory_hostname }} using change_id field
      arista.cvp.cv_change_control_v3:
        state: schedule_and_approve
        change_id: ["{{ cv_change_control_test.data.id }}"]
        schedule_time: "{{ scheduled_time }}"
      register: cv_cc_schedule_and_approve

    - name: Check change control schedule and approve
      # the response doesn't contain any data for schedule
      ansible.builtin.assert:
        that:
          - cv_cc_schedule_and_approve.changed == true
          - cv_cc_schedule_and_approve.data.time is defined
          - cv_cc_schedule_and_approve.data.value.approve.notes == "Initiated from Ansible Playbook"
          - cv_cc_schedule_and_approve.data.value.approve.value == true
          - cv_cc_schedule_and_approve.data.value.key.id == cv_change_control_test.data.id
          - cv_cc_schedule_and_approve.data.value.version is defined
          - cv_cc_schedule_and_approve.failed == false

    - name: Remove a change control on {{ inventory_hostname }} using change_id field
      arista.cvp.cv_change_control_v3:
        state: remove
        change_id: ["{{ cv_change_control_test.data.id }}"]
