# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
# Manual action selection
- name: 'Load tasks for {{ action }}'
  ansible.builtin.include_tasks: "{{ action }}.yml"
