# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
# tasks file for configlets-sync
- name: "Collect facts from {{ inventory_hostname }}"
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Extract shared Configlets"
  ansible.builtin.template:
    src: "template.shared_configlets.j2"
    dest: "{{ common_configlets_dir }}/{{ inventory_hostname }}.yml"
    mode: 0644
  delegate_to: '{{ ansible_runner }}'
  run_once: false

- name: "Check for shared_master"
  ansible.builtin.stat:
    path: '{{ common_configlets_dir }}/master.yml'
  register: status_shared_master
  delegate_to: '{{ ansible_runner }}'

- name: "Create {{ common_configlets_dir }}/master.yml"
  ansible.builtin.file:
    path: '{{ common_configlets_dir }}/master.yml'
    state: touch
    mode: 0644
  when: status_shared_master.stat.exists is false
  delegate_to: '{{ ansible_runner }}'

- name: "Add YAML designators to {{ common_configlets_dir }}/master.yml"
  ansible.builtin.copy:
    content: "---"
    dest: "{{ common_configlets_dir }}/master.yml"
    mode: 0644
  when: status_shared_master.stat.exists is false
  delegate_to: '{{ ansible_runner }}'

- name: "Load Common CVP Servers Configlet Data"
  ansible.builtin.include_vars:
    file: '{{ common_configlets_dir }}/master.yml'
    name: 'shared_master'
  delegate_to: '{{ ansible_runner }}'

- name: "Load CVP Instance Shared Configlet Data"
  ansible.builtin.include_vars:
    file: "{{ common_configlets_dir }}/{{ inventory_hostname }}.yml"
    name: 'shared_server'
  delegate_to: '{{ ansible_runner }}'

- name: "Compare shared Configlets"
  ansible.builtin.template:
    src: "template.compare_configlets.j2"
    dest: "{{ common_configlets_dir }}/master.yml"
    mode: 0644
  delegate_to: '{{ ansible_runner }}'
